---
$schema: "https://github.com/hyperledger-labs/fablo/releases/download/2.2.0/schema.json"
global:
  fabricVersion: "2.5.12"
  tls: false

orgs:
  - organization:
      name: Orderer
      domain: orderer.example.com
    orderers:
      - groupName: group1
        prefix: orderer
        type: solo
        instances: 1
  - organization:
      name: Org1
      domain: org1.example.com
    peer:
      instances: 2
  - organization:
      name: Org2
      domain: org2.example.com
    peer:
      instances: 1

channels:
  - name: my-channel1
    orgs:
      - name: Org1
        peers: [peer0]
      - name: Org2
        peers: [peer0]
  - name: my-channel2
    orgs:
      - name: Org1
        peers: [peer0]
      - name: Org2
        peers: [peer0]

chaincodes:
  - name: duplicateChaincode
    version: "1.0"
    lang: node
    channel: my-channel1
    directory: "./chaincodes/chaincode-kv-node"
    endorsement: "OR('Org1MSP.member', 'Org2MSP.member')"
  - name: duplicateChaincode
    version: "1.0"
    lang: node
    channel: my-channel2
    directory: "./chaincodes/chaincode-kv-node"
    endorsement: "OR('Org1MSP.member', 'Org2MSP.member')"