---
$schema: "https://github.com/hyperledger-labs/fablo/releases/download/2.2.0/schema.json"
global:
  fabricVersion: "2.4.7"
  tls: false

orgs:
  - organization:
      name: Orderer
      domain: orderer.example.com
    orderer:
      type: raft
      instances: 1
  - organization:
      name: Org1
      domain: org1.example.com
    peer:
      instances: 1
    ca:
      prefix: ca
  - organization:
      name: Org2
      domain: org2.example.com
    peer:
      instances: 1
    ca:
      prefix: ca

channels:
  - name: channel1
    orgs:
      - name: Org1
        peers: [peer0]
      - name: Org2
        peers: [peer0]
      - name: Orderer
        peers: []
  - name: channel2
    orgs:
      - name: Org1
        peers: [peer0]
      - name: Org2
        peers: [peer0]
      - name: Orderer
        peers: []

chaincodes:
  - name: duplicateChaincode
    version: "1.0"
    lang: node
    channel: channel1
    directory: "./chaincodes/chaincode-kv-node"
    endorsement: "OR('Org1MSP.member', 'Org2MSP.member')"
  - name: duplicateChaincode
    version: "1.0"
    lang: node
    channel: channel2
    directory: "./chaincodes/chaincode-kv-node"
    endorsement: "OR('Org1MSP.member', 'Org2MSP.member')"